include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-arm.yml'

stages:
  - pre-package
  - package
  - post-package

variables:
  SUBMODULE_PATH: docker-nfs-server

lint-dockerfile:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    DOCKERFILE_PATH: ${SUBMODULE_PATH}/Dockerfile

.docker-build:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    BUILD_CONTEXT: ${SUBMODULE_PATH}

container_scanning:
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    DOCKERFILE_PATH: ${SUBMODULE_PATH}/Dockerfile

.docker-tag-dockerhub:
  variables:
    SOURCE_IMAGE_NAME: ${CI_PROJECT_NAMESPACE}/nfs-server
