include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/docker-build.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/docker-build-arm.yml'

stages:
  - pre-package
  - package
  - post-package

.docker-build:
  variables:
    GIT_SUBMODULE_STRATEGY: normal

.docker-tag-dockerhub:
  variables:
    SOURCE_IMAGE_NAME: ${CI_PROJECT_NAMESPACE}/nfs-server
