services:
  nfs-server:
    image: ${IMAGE_NAME:-pedroetb/nfs-server}:${IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        ALPINE_TAG:
        BASH_VERSION:
        LIBCAP_VERSION:
        NFS_UTILS_VERSION:
