services:
  nfs-server:
    image: ${IMAGE_NAME:-pedroetb/nfs-server}:${IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        ALPINE_TAG:
        BASH_VERSION:
        LIBCAP_VERSION:
        NFS_UTILS_VERSION:
      platforms:
        - linux/amd64
        - linux/386
        - linux/arm64/v8
        - linux/arm/v7
        - linux/arm/v6
